import QueryProvider from '@/app/providers/query-client';
import { AppLayout } from '@/widgets/AppLayout';
import 'antd/dist/antd.css';
import type { Metadata } from 'next';
import StyledComponentsRegistry from '../lib/registry';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='ru'>
      <body>
        <QueryProvider>
          <StyledComponentsRegistry>
            <AppLayout>{children}</AppLayout>
          </StyledComponentsRegistry>
        </QueryProvider>
      </body>
    </html>
  );
}
