import type { Metadata } from "next";
import "./globals.css";
import "antd/dist/antd.css";
import StyledComponentsRegistry from "../lib/registry";
import QueryProvider from "@/app/providers/query-client";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body>
        <QueryProvider>
          <StyledComponentsRegistry>{children}</StyledComponentsRegistry>
        </QueryProvider>
      </body>
    </html>
  );
}
